### ISSUE TITLE
页码问题和信件

### ISSUE THREAD

**Issue by zengmiaokun** [xjtu-blacksmith/easymcm#1]
页码有点小问题，好像参考文献需要另起一页的。参考文献和附录不计入总页码。

没有信件部分的模板其实这个需求还是很大的。

**Comment by xjtu-blacksmith** [comment]
1. COMAP对于页码并没有要求，目前通行的`LaTeX`模板中均将参考文献和附录记入正文部分（并计页码），刚刚有用户说看往年的论文中也大部分是这样操作的。其实主要的问题是，`LaTeX`中对页码的处理不便。不过，如果之后有时间，我会尝试着修改这一部分，提供一个*可选项*。
2. 信件的格式很简单，只需要加一个`\section*`并配合若干居左居右的盒子即可。一般用户都能够自己填写的。

**Comment by zengmiaokun** [comment]
是的，我看了其他的模板也是这样，非常感谢你的辛苦维护。
目前还遇到一个问题就是目录中的参考文献和附录部分的超链接只能跳转到正文的尾部。

**Comment by xjtu-blacksmith** [comment]
在目前版本（`v5.1`）中：

- 页码未作调整，主要是 `lastpage` 宏包很难调整。仍遵从往年惯例。
- 已加入信件/备忘录环境，并在 `PAPER.tex` 中演示了其用法。
- 目录超链接跳转问题已通过 `\refcounter` 等命令修正。

本问题将关闭，如有其他问题请开新 issue。感谢！
