### ISSUE TITLE
Summary: issues 汇总

### ISSUE THREAD

**Issue by xjtu-blacksmith** [xjtu-blacksmith/easymcm#2]
# 美赛模板收到问题汇总
- 摘要超过一页如何处理，或如何扩充摘要页的可用面积
- 如何定制Summary sheet样式
- 修改全文的基础字号
- 修改行距/段间距
- 如何修改总页数（不计References），及其他的页码调整问题
- 首页标题不能换行（即将修正）
- 定制目录样式——可以用`tocloft`宏包解决吗？
- 转义字符
- 引用如何变成上标
- 表格/图片能否换行？浮动环境怎么回事？
- 插入Memo/Letter等
- 公式的`\frac`与`\dfrac`之别
- pdf文件损坏
- 编译器配置不正确（无法运行某命令）
- 编码问题，unicode文件无法编译；多出BOM头
- 终极问题：为什么用个`LaTeX`有这么多坑？

**进一步更新之前，应当读好各种参考文献。**

**Comment by iydon** [comment]
- 摘要应符合字面意思, 将重要的内容思路与结果写出来, 记得在 TeX 群里讨论过美赛摘要是否需要超过一页. 如果实在差几行放不下, 可以使用 `\enlargethispage`, 或者修改 `\geometry{...}`.
- Summary sheet 样式在你们惨开的 [mcmthesis](https://github.com/Liam0205/mcmthesis) 里提及到, 可以查一下文档.
- 修改全文的基础字号等问题在 [lshort](https://ctan.org/pkg/lshort-zh-cn) 中有提及, 可以参考一下.
- 定制目录样式的宏包 [tocloft 文档](https://ctan.org/pkg/tocloft) 中有详细说明.
- 引用变上标可以参考 `natbib`, `biblatex` 等宏包, 不必都使用, 选择一个即可.
- 浮动环境也在 [lshort](https://ctan.org/pkg/lshort-zh-cn) 中有提及, 可以说这是 LaTeX 的精髓之一.
- 插入 Memo 在2019年美赛的 [mcmthesis](https://github.com/Liam0205/mcmthesis) 已经实现.
- 觉得 LaTeX 坑可能是没有系统学过, 2019年秋季学期写过一份 [LaTeX 资源及学习路径](http://tex.readthedocs.io/), 如果有兴趣可以帮忙提问补充, 谢谢.

**Comment by xjtu-blacksmith** [comment]
> 
> 
>     * 摘要应符合字面意思, 将重要的内容思路与结果写出来, 记得在 TeX 群里讨论过美赛摘要是否需要超过一页. 如果实在差几行放不下, 可以使用 `\enlargethispage`, 或者修改 `\geometry{...}`.
> 
>     * Summary sheet 样式在你们惨开的 [mcmthesis](https://github.com/Liam0205/mcmthesis) 里提及到, 可以查一下文档.
> 
>     * 修改全文的基础字号等问题在 [lshort](https://ctan.org/pkg/lshort-zh-cn) 中有提及, 可以参考一下.
> 
>     * 定制目录样式的宏包 [tocloft 文档](https://ctan.org/pkg/tocloft) 中有详细说明.
> 
>     * 引用变上标可以参考 `natbib`, `biblatex` 等宏包, 不必都使用, 选择一个即可.
> 
>     * 浮动环境也在 [lshort](https://ctan.org/pkg/lshort-zh-cn) 中有提及, 可以说这是 LaTeX 的精髓之一.
> 
>     * 插入 Memo 在2019年美赛的 [mcmthesis](https://github.com/Liam0205/mcmthesis) 已经实现.
> 
>     * 觉得 LaTeX 坑可能是没有系统学过, 2019年秋季学期写过一份 [LaTeX 资源及学习路径](http://tex.readthedocs.io/), 如果有兴趣可以帮忙提问补充, 谢谢.

收到，以上的「问题汇总」是对当时通过邮件咨询我的若干问题的整合。`easymcm` 模板的已知问题基本上都已经解决过了（我也已在 `latexstudio` 的 `mcmthesis` 分支中提交了改动，同样的改动应该会合并到 Liam Huang 的主分支上去）。

感谢您的一一解答，我会在注明作者的前提下将您的回答 merge 到发布页面（或相关页面）上，并推荐您关于 TeX 的 rtd。今年已不打算再应付从邮箱发来的缺乏准备的问题。

**Comment by xjtu-blacksmith** [comment]
检查之前问题，大多为 LaTeX 学习方面问题，不属于本宏包相关问题。相关问题已在新版本中解决。仅此。
