### ISSUE TITLE
Abstract Issue

### ISSUE THREAD

**Issue by Rain1560** [xjtu-blacksmith/easymcm#20]
摘要部分不能自动换行，超出行号的溢出页面。

**Comment by xjtu-blacksmith** [comment]
您好，请您更清晰地描述问题，最好能提供代码实例或输出文件的截图。不确定您说的“行号”是什么，正常情况下摘要里并没有行号？

**Comment by Rain1560** [comment]
在easymcm.sty中，与摘要页面相关的代码好像是这样：
% abstract 环境的设置
\newbox\@abstract   % 将摘要创建为盒子

\setbox\@abstract\hbox{}  % 盒子置空
\long\def\abstract{
\bgroup\global\setbox\@abstract\vbox\bgroup
\hsize\textwidth
}

\def\endabstract{\egroup\egroup}

\def\make@abstract{
    \vskip -10pt\par
    {\centering\Large\bfseries\@title\vskip1ex}\par  % 插入论文标题，字号可自己修改
    {\centering\bfseries\abstractname\vskip1.5ex}\par  %摘要标题
    \noindent\usebox\@abstract\par  % 摘要正文
    \vskip 10pt
}  % 底部留空，若不需要可删去

% Summary Sheet 生成
\def\@maketitle{
	\makesheet
	\make@abstract
    \pagestyle{empty}
    \newpage
}

% 目录生成
\renewcommand\tableofcontents{%
    \centerline{\normalfont\Large\bfseries\contentsname%
    \@mkboth{%
    \MakeUppercase\contentsname}{\MakeUppercase\contentsname}}%
    \vskip 3ex%
    \@starttoc{toc}%
    \thispagestyle{fancy}
    \clearpage
    \pagestyle{fancy}
    \setlength\parskip{1ex}}  % 调整段间距

\endinput

在main.tex中，摘要部分如下：
\begin{abstract}
tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt    
\end{abstract}
明显一行塞不下长文本，溢出的部分不会自动换行，(pdflatex)编译成pdf以后超出了页面：
![image](https://user-images.githubusercontent.com/96043131/219526995-6bb9d443-14ab-407f-a162-b4e0bae37135.png)

**Comment by xjtu-blacksmith** [comment]
并不理解您为何要以此举例，您输入的是一个超长的单词，并且 TeX 无法自动判断该单词的断行位置，所以发生了您所谓的“溢出”现象。正常的英文句子都应该是可以正常换行的，我这边刚刚也重新测试了，并无问题。

![图片](https://user-images.githubusercontent.com/42454373/219528320-56920aef-dc14-4a5b-922b-fdc2299663ab.png)

您是否是想在摘要中放入 verbatim 一类的代码抄录环境？如果是这样的话，可能确实存在不能换行的问题。但这个问题是由这类环境本身决定的，与摘要这里的设置无关。

**Comment by Rain1560** [comment]
看来是单词过长的问题。多谢回复。
